name: 'pr-commit-messages-action'
description: 'get PR commit messages'
outputs:
  commits:
    description: 'PR commit messages'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-pull-request'
  color: 'red'
